name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update major version tag
        uses: richardsimko/update-tag@aab2434e9a5040687874aa39d1c6377ec0cb0d94
        with:
          tag_name: v0
        env:
          GITHUB_TOKEN: ${{ github.token }}